routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group( array('prefix' => 'admin','middleware' => 'role'), function(){
    Route::get('/',  function () {
        return view('admin.admin');
    });
    Route::resource('posts', 'PostsController');
});

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Posts extends Model
{
    protected $table = "posts";

    protected $fillable = ['uid','title','img','small_titl1','small_tip1','small_titl2','small_tip2','middle_title','type','tags','active'];

    public static function store($request,$user_id ,$imagename){
        $post = new Posts();
        if($request->title){
            $post->title = $request->title;
        }
        if($user_id){
            $post->uid = $user_id;
        }
        if($imagename){
            $post->img = $imagename;
        }
        if($request->small_titl1){
            $post->small_titl1 = $request->small_titl1;
        }
        if($request->small_tip1){
            $post->small_tip1 = $request->small_tip1;
        }
        if($request->small_titl2){
            $post->small_titl2 = $request->small_titl2;
        }
        if($request->small_tip2){
            $post->small_tip2 = $request->small_tip2;
        }
        if($request->middle_title){
            $post->middle_title = $request->middle_title;
        }
        if($request->type){
            $post->type = $request->type;
        }
        if($request->tags){
            $tags = implode( ", ", $request->tags);
            $post->tags = $tags;
        }
        if($request->active){
            $post->active = $request->active;
        }
        if($request->active == "1"){
            $post->active = $request->active;
        }else{
            $post->active = "0";
        }
        $post->save();
        return $post;
    }
    public static function _update($request, $id, $imageName)
    {
        if(empty($imageName) || !$imageName){
            $imageName = $request->old_img;
        }
        $tags = implode( ", ", $request->tags);
        $post = Posts::find($id);
        $post->title = $request->title;
        $post->uid = $id;
        $post->img = $imageName;
        $post->small_titl1 = $request->small_titl1;
        $post->small_tip1 = $request->small_tip1;
        $post->small_titl2 = $request->small_titl2;
        $post->small_tip2 = $request->small_tip2;
        $post->middle_title = $request->middle_title;
        $post->type = $request->type;
        $post->tags = $tags;
        if($request->active == "1"){
            $post->active = $request->active;
        }else{
            $post->active = "0";
        }
        $post->save();
        return $post;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }

}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Posts;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_id = auth()->user()->id;
        $posts = Posts::where('uid',$user_id)->paginate(10);
        return view('admin.allPosts',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.addPost');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $user_id = auth()->user()->id;
        if ($request->hasFile('img')) {
            if ($request->file('img')->isValid()) {
                try {
                    $file = $request->file('img');
                    $path = 'images/uploads';
                    $iname = rand(11111, 99999) . '.' . $file->getClientOriginalExtension();
                    $name = $path . '/' . $iname;
                    $request->file('img')->move(public_path($path), $iname);

                } catch (Illuminate\Filesystem\FileNotFoundException $e) {

                }
            }
        }else {
            $name = '';
        }
        $store = Posts::store($request,$user_id,$name);
        return redirect()->route("posts.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.viewPost');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Posts::find($id);
        return view('admin.editPost',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->hasFile('img')) {
            if ($request->file('img')->isValid()) {
                try {
                    $file = $request->file('img');
                    $path = 'images/uploads';
                    $iname = rand(11111, 99999) . '.' . $file->getClientOriginalExtension();
                    $name = $path . '/' . $iname;
                    $request->file('img')->move(public_path($path), $iname);

                } catch (Illuminate\Filesystem\FileNotFoundException $e) {

                }
            }
        }else {
            $name = $request->img;
        }
        $store = Posts::_update($request,$id,$name);
        return redirect()->route("posts.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Posts::destroy($id);
        return redirect()->route('posts.index');
    }
}

resources/views/admin/addPost.blade.php
@extends('layouts.adminApp')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info text-light" href="{{ route('posts.index') }}">ALL POSTS</a>
            </div>
        </div>
        <div class="row justify-content-center pt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Add New Post</div>
                    <div class="card-body">
                        <form action="{{ route('posts.store') }}" enctype="multipart/form-data" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" name="title" class="form-control" id="title" required>
                            </div>
                            <div class="form-group">
                                <label for="img">Image</label>
                                <input type="file" name="img" class="form-control-file" id="img" required>
                            </div>
                            <div class="form-group">
                                <label for="small_titl1">Small Title 1</label>
                                <input type="text" name="small_titl1" max-length="50" class="form-control" id="small_titl1">
                            </div>
                            <div class="form-group">
                                <label for="small_tip1">Small Tip 1</label>
                                <input type="text" name="small_tip1" max-length="1000" class="form-control" id="small_tip1">
                            </div>
                            <div class="form-group">
                                <label for="small_titl2">Small Title 2</label>
                                <input type="text" name="small_titl2" max-length="50" class="form-control" id="small_titl2">
                            </div>
                            <div class="form-group">
                                <label for="small_tip2">Small Tip 2</label>
                                <input type="text" name="small_tip2" max-length="1000" class="form-control" id="small_tip2">
                            </div>
                            <div class="form-group">
                                <label for="middle_title">Middle Title</label>
                                <input type="text" name="middle_title" max-length="60" class="form-control" id="middle_title">
                            </div>
                            <div class="form-group">
                                <label for="type">Type</label>
                                <select class="form-control" name="type" id="type">
                                    <option value="A1">A1</option>
                                    <option value="A2">A2</option>
                                    <option value="B1">B1</option>
                                    <option value="B2">B2</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <div>
                                    <label>Tags</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t1" value="T1">
                                    <label class="form-check-label" for="t1">T1</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t2" value="T2">
                                    <label class="form-check-label" for="t2">T2</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t3" value="T3">
                                    <label class="form-check-label" for="t3">T3</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="b1" value="B1">
                                    <label class="form-check-label" for="b1">B1</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="b2" value="B2">
                                    <label class="form-check-label" for="b2">B2</label>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <label for="active">Active</label>
                                    </div>
                                    <label class="switch">
                                        <input type="checkbox" name="active" id="active" value="1" checked>
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                <div class="form-group col-md-4 m-auto">
                                    <input type="submit" name="" class="btn btn-success btn-block" value="Create" id="">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/admin.blade.php
@extends('layouts.adminApp')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/allPosts.blade.php
@extends('layouts.adminApp')
@section('style')
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info text-light" href="{{ route('posts.create') }}">ADD NEW</a>
            </div>
        </div>
        <div class="row justify-content-center pt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">All Posts ({{ $posts->total() }}) . <span>Showing {{ $posts->count() }} on this page.</span> </div>
                    <div class="card-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Image</th>
                                    <th scope="col">Small Title 1</th>
                                    <th scope="col">Small Tip 1</th>
                                    <th scope="col">Small Title 2</th>
                                    <th scope="col">Small Tip 2</th>
                                    <th scope="col">Medium Title</th>
                                    <th scope="col">Type</th>
                                    <th scope="col">Tags</th>
                                    <th scope="col">Active</th>
                                    <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {{--{{ dd($posts) }}--}}
                            @foreach($posts as $key=>$post)
                                <tr>
                                    <th scope="row">{{$post->id}}</th>
                                    <td>{{$post->title}}</td>
                                    <td><img src="{{asset($post->img)}}" height="30"></td>
                                    <td>{{$post->small_titl1}}</td>
                                    <td>{{$post->small_tip1}}</td>
                                    <td>{{$post->small_titl2}}</td>
                                    <td>{{$post->small_tip2}}</td>
                                    <td>{{$post->middle_title}}</td>
                                    <td>{{$post->type}}</td>
                                    <td>{{$post->tags}}</td>
                                    <td>{{$post->active}}</td>
                                    <td class="actions">
                                        <a href="{{ route('posts.edit',$post->id) }}" class="edit_icon"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="trash_icon btn btn-light"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $posts->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="https://code.jquery.com/jquery-3.4.1.slim.js" integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI=" crossorigin="anonymous"></script>
    <script>
        $('.trash_icon').on('click',function(e){
            e.preventDefault();
            if(confirm("Are you sure?")){
                $(this).parent().submit()
            }
        })
    </script>
@endsection

resources/views/admin/editPost.blade.php
@extends('layouts.adminApp')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <a class="btn btn-info text-light" href="{{ route('posts.index') }}">ALL POSTS</a>
            </div>
        </div>
        <div class="row justify-content-center pt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Edit Post</div>

                    <div class="card-body">
                        <form action="{{ route('posts.update',$post->id) }}" enctype="multipart/form-data" method="post">
                            @csrf
                            @method("PUT")
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" name="title" class="form-control" id="title" value="{{ $post->title }}" required>
                            </div>
                            <div class="form-group flex">
                                @if(!empty($post->img))
                                    <div class="post_thumb">
                                        <img src="{{ asset($post->img) }}" width="50" alt="">
                                    </div>
                                    <div class="edit_thumb">
                                @endif
                                <div>
                                    <label for="img">Image</label>
                                    <input type="file" name="img" class="form-control-file" id="img" value="{{ $post->img }}">
                                    <input type="hidden" name="old_img" value="{{ $post->img }}">
                                </div>
                                @if(!empty($post->img))
                                    </div>
                                @endif
                            </div>
                            <div class="form-group ">
                                <label for="small_titl1">Small Title 1</label>
                                <input type="text" name="small_titl1" max-length="50" class="form-control" value="{{ $post->small_titl1 }}" id="small_titl1">
                            </div>
                            <div class="form-group">
                                <label for="small_tip1">Small Tip 1</label>
                                <input type="text" name="small_tip1" max-length="1000" class="form-control" value="{{ $post->small_tip1 }}" id="small_tip1">
                            </div>
                            <div class="form-group">
                                <label for="small_titl2">Small Title 2</label>
                                <input type="text" name="small_titl2" max-length="50" class="form-control" value="{{ $post->small_titl2 }}" id="small_titl2">
                            </div>
                            <div class="form-group">
                                <label for="small_tip2">Small Tip 2</label>
                                <input type="text" name="small_tip2" max-length="1000" class="form-control" value="{{ $post->small_tip2 }}" id="small_tip2">
                            </div>
                            <div class="form-group">
                                <label for="middle_title">Middle Title</label>
                                <input type="text" name="middle_title" max-length="60" class="form-control" value="{{ $post->middle_title }}" id="middle_title">
                            </div>
                            <div class="form-group">
                                <label for="type">Type</label>
                                <select class="form-control" name="type" id="type">
                                    <option value="A1" {{ $post->type ==  "A1" ? 'selected':''}}>A1</option>
                                    <option value="A2" {{ $post->type ==  "A2" ? 'selected':''}}>A2</option>
                                    <option value="B1" {{ $post->type ==  "B1" ? 'selected':''}}>B1</option>
                                    <option value="B2" {{ $post->type ==  "B2" ? 'selected':''}}>B2</option>
                                </select>
                            </div>
                            <div class="form-group">
                                @php($tags = explode(', ' ,$post->tags))
                                <div>
                                    <label>Tags</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t1" value="T1" {{ in_array('T1',$tags)?"checked":"" }}>
                                    <label class="form-check-label" for="t1">T1</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t2" value="T2" {{ in_array('T2',$tags)?"checked":"" }}>
                                    <label class="form-check-label" for="t2">T2</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="t3" value="T3" {{ in_array('T3',$tags)?"checked":"" }}>
                                    <label class="form-check-label" for="t3">T3</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="b1" value="B1" {{ in_array('B1',$tags)?"checked":"" }}>
                                    <label class="form-check-label" for="b1">B1</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="tags[]" id="b2" value="B2" {{ in_array('B2',$tags)?"checked":"" }}>
                                    <label class="form-check-label" for="b2">B2</label>
                                </div>
                                <div class="form-group">
                                    <div>
                                        <label for="active">Active</label>
                                    </div>
                                    <label class="switch">
                                        <input type="checkbox" name="active" id="active" value="1" {{ $post->active ? "checked" : "" }}>
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                                <div class="form-group col-md-4 m-auto">
                                    <input type="submit" name="" class="btn btn-success btn-block" value="Update" id="">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/viewPost.blade.php
@extends('layouts.adminApp')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">View</div>

                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(Auth::user())
                        {{ "Hello " . Auth::user()->name }},
                        You are logged in!
                    @else
                        Please <a href="/login">log in</a> to start
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/adminApp.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    @yield('style')
</head>
<body>
    @if(Auth::user() && Auth::user()->role)
        <div class="admin_panel">
            <a href="/admin" class="admin_panel_link">Go to Dashboard</a>
            <div class="dropdown">
                <a id="navbarDropdown" class="admin_panel_link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    @endif
    <div class="main">
        <div class="left_side">
            <ul class="admin_nav">
                <li><a href="{{ route('posts.index') }}">All Posts</a></li>
            </ul>
        </div>
        <div class="content">
            @yield('content')
        </div>
    </div>
    @yield('script')
</body>
</html>